version: '3'

services:
  web:
    build: ./containers/web
    image: app/web
    container_name: rails-trb-web
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    environment:
      BUNDLE_PATH: /app/vendor/bundle/ruby/2.5.0
    depends_on:
      - db
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"

  db:
    build: ./containers/db
    image: app/db
    container_name: rails-trb-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: "Asia/Tokyo"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "3306:3306"
